on:
  push:
    branches:
    - main
    - release/*
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: "6.5.*"
      - name: Checkout fritzing
        run: git clone https://github.com/fritzing/fritzing-app
      - name: Checkout libgit2
        run: git clone https://github.com/libgit2/libgit2
      - uses: ilammy/msvc-dev-cmd@v1
      - name: Build libgit2
        run: cd libgit2 && mkdir build64 && cd build64 && cmake -DCMAKE_BUILD_TYPE=Release .. && cmake --build . && xcopy /E .\Debug .\Release
        shell: cmd
      - name: Do stuff
        run: cd fritzing-app && mkdir build && cd build && qmake ..\phoenix.pro && make
        shell: cmd
