on:
  push:
    branches:
    - main
    - release/*
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.9
      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: "6.5.*"
      - name: Checkout fritzing
        run: git clone https://github.com/fritzing/fritzing-app
      - name: Checkout libgit2
        run: git clone https://github.com/libgit2/libgit2
      - uses: ilammy/msvc-dev-cmd@v1
      - name: Build libgit2
        run: cd libgit2 && mkdir build64 && cd build64 && cmake -DCMAKE_C_COMPILER_LAUNCHER=sccache -DCMAKE_CXX_COMPILER_LAUNCHER=sccache -DCMAKE_BUILD_TYPE=Release .. && cmake --build . && xcopy /E /I .\Debug .\Release
        shell: cmd
      - name: Install Boost
        run: curl https://archives.boost.io/release/1.85.0/source/boost_1_85_0.zip -L > boost_1_85_0.zip && tar xf boost_1_85_0.zip
        shell: cmd
      - name: Download ngspice
        run: curl -L https://sourceforge.net/projects/ngspice/files/ng-spice-rework/44/ngspice-44.tar.gz/download > ngspice-44.tar.gz && "C:\Program Files\Git\usr\bin\tar.exe" xzf ngspice-44.tar.gz
        shell: cmd
      - name: Build ngspice
        run: cd ngspice-44 && ./compile_min.sh
        shell: bash
      - name: Do stuff
        run: cd fritzing-app && mkdir build && cd build && qmake ..\phoenix.pro && make
        shell: cmd
